Project News site magazine
Technigo/project-news-site pull request #101
Opened 2020-08-30 19:18 UTC by JHarde

https://footballnewsproject.netlify.app/

2020-09-04 17:46 UTC, bealun requested changes
This site will turn anyone into a football fan! You've done a really nice job making everything look good with the hover effects, the little animation and the header links 👏 
There are some smaller changes requested regarding the tablet/iPad styling for your site. The header goes outside your content but it's an easy fix if you inspect and maybe wrap whatever it is that's making it push out. Have a look and then you'll be approved!
Still amazing work this week and be really proud of yourself 🎉

2020-09-04 17:46 UTC, bealun commented on code/index.html
> +    <link rel="icon" type="image/png" href="./">
Was this about to become a favicon? Next project? 😎

2020-09-04 17:46 UTC, bealun commented on code/index.html
> +          <li class="nav-logo"><a href="https://www.fotbollskanalen.se/" target="_blank"><img src="./images/fk_logo.png" alt="Fotbollskanalen logo"/></a></li>
Really nice to open links in new tab 👏

2020-09-04 17:46 UTC, bealun commented on code/index.html
> +      <div class="news-card-image"><img src="./images/messi.jpg" alt="Lionel Messi"/></div>
Nice structure with image folder!

2020-09-04 17:46 UTC, bealun commented on code/index.html
> +      <div class="news-child"><img src="./images/messiballon.jpg" alt="Ballon dór"/><p>The one and only six time winner of Ballon dór</p></div>
These could use some indentation and structure however 🙃 But good use of alt in the image tags!!

2020-09-04 17:46 UTC, bealun commented on code/style.css
> +  box-sizing: border-box;
BRAVO!! So you don't need to repeat code 💫

2020-09-04 17:46 UTC, bealun commented on code/style.css
> +.news-child >p:hover  {
Gotta love hover effects 🥳

2020-09-04 17:46 UTC, bealun commented on code/style.css
> +  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
Really nice UI feature 🙌

2020-09-04 17:46 UTC, bealun commented on code/style.css
> +.news-child:hover  {
This is so good 👏👏👏

2020-09-10 10:47 UTC, JHarde reviewed
Have made some minor changes now, let me now if there is anything else I need to change.

2020-09-10 10:52 UTC, bealun approved these changes

2021-01-13 16:38 UTC, closed without merging