Project 1 - Mabel
Technigo/project-news-site pull request #122
Opened 2021-01-23 08:29 UTC by Mabelliaw123

I have a hard time creating Flexbox, whereby Media Q doesn't work at the end. What I did was, redo ing yet again. 
The changes updated made could be undefined, due to the repetition changes constantly. 
Nevertheless I create a simple website which focused on the code rather than the content itself. 

Mvh/ Mabel

2021-01-29 14:30 UTC, HIPPIEKICK commented
Hi Mabel! Did you deploy your project to netlify? Could you provide a link? :)

2021-01-29 18:04 UTC, Mabelliaw123 commented
Hi Matilda!

Yes, here it is .
https://compassionate-hodgkin-c24e80.netlify.app/code/

Mvh/Mabel

On Fri, 29 Jan 2021 at 15:31, Matilda Arvidsson <notifications@github.com>
wrote:

> Hi Mabel! Did you deploy your project to netlify? Could you provide a
> link? :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-news-site/pull/122#issuecomment-769838765>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQWGYBOQE64RWVTC4ZSLKIDS4LBC3ANCNFSM4WPQG7YA>
> .
>

2021-02-02 10:02 UTC, HIPPIEKICK requested changes
Good job on this project Mabel! I would like to ask you to go through your HTML document again and give all nested elements new lines. Take a look at the [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) if you want to recap :)

Also, take a look at my comment about horizontal scroll. Fix these things and you're good to go!

We’ve also put together some general feedback that applies to many projects this first week. Check it out and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-02-02 10:02 UTC, HIPPIEKICK commented on code/index.html
> +            <div class="news-cardthree"><b>
Try to go with kebab-case for all the class names, for better readability

2021-02-22 14:39 UTC, closed without merging