Project 2 - Mette Wickert
Technigo/project-news-site pull request #123
Opened 2021-01-23 09:12 UTC by ettem

My focus during the project was to finish the blue level goals but I also touched at least partly the red and black goals as well.

I had a hard time getting my connection to Github work, pushing the updates from VSC. Somehow I managed to delete my code in the clone I was working on, but I fixed it I think and hope everything is ok and works as it should so you can do a review.

I also struggled hard with flexbox and margins and paddings, hence I've added some classes and id's that probably could be merged together so the code will be less repetitive. Perhaps you have som advice concerning that. Also I like to get clarified concerning using id's for styling - should I stop using them and only use classes?

2021-01-29 14:47 UTC, HIPPIEKICK requested changes
Good job with this project Mette! I really like the topic and the colors 🤩 As you mentioned, your code is a little repetitive but I gave you some comments on how you can think about that. I would like to ask you take a look at your formatting, so new line (and indentation) for each nested HTML element. Also, take a look at the indentation of your CSS file. For further reference - [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e). Change this and you're approved :)

We’ve also put together some general feedback that applies to many projects this first week. Check it out and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/index.html
> +          <div class="nav-item"><a href="#">Contact</a></div>
Do you need these wrapping `div`s or would it be enough with just the links? If you decide to keep, give nested elements new lines:
```
<div>
  <a></a>
</div>
```

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/index.html
>      <section class="big-news">
Some unnecessary blank lines here

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/index.html
> +          <p id="big-news-p">Lorem ipsum dolor sit amet consectetur adipisicing elit. A vel, similique inventore necessitatibus eaque dolores. Molestiae quae aliquam voluptates totam neque alias aspe
Ids are mostly used for JavaScript, so to answer your question you could stick to style classes :) Read more in this weeks general feedback document :👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/index.html
> +          <a href="#"><img id="img-big" src="https://images.unsplash.com/photo-1499728603263-13726abce5fd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=150
New line

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/style.css
> +  }
Check indentation of your CSS file, only the properties should be indented here, not the whole element :)

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/style.css
> +  }
Ids have to be unique, but for CSS it's more common to style by classes as mentioned, so you could give all these elements the same class and shorten this to one row

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/style.css
> +  }
Same here. If you were to style many elements in the same way though, you could do it with a comma:
```
.element-1, .element-2 {
  color: red;
}
```

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/style.css
> +    padding: 10px;
10px is a bit small and hard to read 👀

2021-01-29 14:47 UTC, HIPPIEKICK commented on code/style.css
> +
If you add:
```
body {
  margin: 0;
}
```
your image header would go all the way to the edges :)

2021-01-29 14:48 UTC, HIPPIEKICK commented on code/style.css
> +  }
🤩

2021-01-29 21:23 UTC, ettem commented
Thank you Matilda for your good and constructive review! I have updated and pushed the changes you requested, I hope I interpreted them correctly :) Also, Github is not my friend yet so I hope I've done this right so you can see the changes.

2021-02-08 10:48 UTC, HIPPIEKICK commented on code/index.html
> +          <a href="#"><img id="img-big" src="https://images.unsplash.com/photo-1499728603263-13726abce5fd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=150
<a href="#">
  <img id="img-big" src="https://images.unsplash.com/photo-1499728603263-13726abce5fd?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80" alt="image with phrase mindfulness" />
</a>

2021-02-08 10:50 UTC, HIPPIEKICK commented on code/style.css
> +font-family: verdana, sans-serif;
These two lines too 😇

2021-02-08 10:51 UTC, HIPPIEKICK commented
> Thank you Matilda for your good and constructive review! I have updated and pushed the changes you requested, I hope I interpreted them correctly :) Also, Github is not my friend yet so I hope I've done this right so you can see the changes.

Yes, you've got the hang of it 💯  Approving!

2021-02-08 10:51 UTC, HIPPIEKICK approved these changes

2021-08-10 11:48 UTC, closed without merging