Project Week 2
Technigo/project-news-site pull request #137
Opened 2021-01-24 11:18 UTC by jessika-hage

2021-01-30 17:29 UTC, JennieDalgren requested changes
Really nice job with this project!

The only thing I would like you to change to be approved is the indentation in the html file. Also try to use more semantic html tags, not only divs 😉
Yes, we're a bit picky with tidying the code. That's just so that you'll get into good habit of writing neat and clean code!

Take a look at [our code guidelines.](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e)
We’ve also put together some general feedback that applies to many projects this first week. Check it out and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

All in all a very good project!
Keep up the good work 🥇

2021-01-30 17:29 UTC, JennieDalgren commented on code/style.css
> +/* Navigation bar and dropdown for mobile phones */
good job with comments like this!

2021-02-04 21:27 UTC, jessika-hage commented
I think I fixed the needed changes now! :)

2021-02-07 12:14 UTC, JennieDalgren commented on code/style.css
> +  animation: logo 1s alternate-reverse infinite;
⭐

2021-02-07 12:15 UTC, JennieDalgren approved these changes
💯

2021-08-10 11:48 UTC, closed without merging