Elle Frankenberg- news site
Technigo/project-news-site pull request #142
Opened 2021-01-24 13:24 UTC by ElleFrankenberg

2021-01-29 17:54 UTC, JennieDalgren commented
Hi! Do you have a deployed version of this? Please provide a link to the project 🙂

2021-01-29 18:01 UTC, ElleFrankenberg commented
> Hi! Do you have a deployed version of this? Please provide a link to the project 🙂

Hi! Here is the link :) https://quizzical-fermi-345eed.netlify.app

2021-01-31 17:16 UTC, JennieDalgren requested changes
Good job with your project.

For next time, try to commit more often and with descriptive commit messages.

To be able to approve this project you should fix the indentation in your code.

Take a look at [the code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) if you need and change this.
We’ve also put together some general feedback that applies to many projects this first week. Check it out and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

really nice job with the styling, I like the design!
keep it up ⭐️

2021-01-31 17:16 UTC, JennieDalgren commented on README.md
>  Every project should be deployed somewhere. Be sure to include the link to the deployed project so that the viewer can click around and see what it's all about.
this is where you should add your link, for future projects

2021-01-31 17:16 UTC, JennieDalgren commented on code/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
⭐

2021-01-31 17:16 UTC, JennieDalgren commented on code/index.html
> +        <div class="hamburger">
seems like this div doesnt have a closing tag?

2021-01-31 17:16 UTC, JennieDalgren commented on code/index.html
> +      <div class="main-plant-artikle">
seems like you have a section with the classname _main plant container_ but then just a div with the class name _main plant artikle_ in that. You could just keep one of them, preferable the section as it is a more semnatic element than a div.

2021-01-31 17:16 UTC, JennieDalgren commented on code/index.html
> +      <section class="other-plant-cards">
again here with sections...
Do they all have closing tags?

2021-01-31 17:16 UTC, JennieDalgren commented on code/style.css
> +margin: 20px 0px 5px 0px;
indentation

2021-01-31 17:16 UTC, JennieDalgren commented on code/style.css
> +
remove blank line

2021-02-01 08:56 UTC, ElleFrankenberg commented
Hi! Now I have fixed the required changes :) (I hope)

2021-02-04 11:31 UTC, JennieDalgren commented
Hey, I can see that you've made changes but I can't access the html or css files any more. Are you sure they are still there, in your repo?

2021-02-05 12:46 UTC, ElleFrankenberg commented
Hi! now I believe the html and css is in the repo (I hope)

2021-02-07 12:13 UTC, JennieDalgren approved these changes
💯

2021-08-10 11:48 UTC, closed without merging