Project 2 - Ati Takrami
Technigo/project-news-site pull request #144
Opened 2021-01-24 14:31 UTC by takrami

:pushpin: I covered all items in 3 levels (Blue, Red, Black). There is one item that I decided to not to implement on Black level which is `CSS-grid`. The reason behind that is, I had experience to use `CSS-grid` before. So, I decided to use `CSS-flex` which I was less experienced in. I also added some non-mandatory things like:
- [X] CSS variables
- [X] CSS functions
- [X] Decoupled the stylesheet file into more readable and structured files.  
- [X] Used font awesome for icons (as it will take less resources to loads and leads to faster end user experience)
- [X] Used google fonts
- [X] Added minor JavaScript function to makes menu more responsive on mobile/tablet device.
- [X] Used `normalize` css file.
- [X] I used Figma to design the whole page before coding. [The design is available here](https://www.figma.com/file/kxwhrnL9gmhk29Dc1X8dPG/dev-news?node-id=1%3A2).

2021-02-03 16:29 UTC, EmOlsz requested changes
Hey Ati!
Great job, you did very solid first project :)
There are some (relatively small) things I would like you to fix - take a look at my comments and provide necessary changes. After that, I'll be able to approve your pull request.
Moreover, take a look at our 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)!

2021-02-03 16:29 UTC, EmOlsz commented on code/app.js
> +  var menu = document.getElementById("main-menu-cnt");
Let's try to remember about avoiding `var` keyword - there is really small amount of use cases when we should use it :) By default, we should aim for `const`

2021-02-03 16:29 UTC, EmOlsz commented on code/assets/css/footer.css
> +  color: var(--primaryColorDarker);
Great job with CSS variables! :) really impressive

2021-02-03 16:29 UTC, EmOlsz commented on code/assets/css/general.css
> +  -webkit-box-shadow: 0px 1px 3px 0px rgba(120, 120, 120, 0.22);
Good that you remember about all important browsers 👍

2021-02-03 16:29 UTC, EmOlsz commented on code/assets/css/header.css
> +#main-menu-cnt {
We shouldn't style by id's - let's add class to that HTML element and style by it

2021-02-03 16:29 UTC, EmOlsz commented on code/assets/css/homepage.css
> +    /* margin: calc(var(--spacing) * 2); */
Another commented code - let's remove it

2021-02-03 16:29 UTC, EmOlsz commented on code/index.html
> +    <script src="./app.js"></script>
It can be really tricky to apply `script` in `<head />` - far more safe to place it at the end of `<body />`

2021-02-03 16:29 UTC, EmOlsz commented on code/index.html
> +              <img src="./assets/logo.svg" alt="" />
It doesn't really makes sense to apply empty `alt` attribute - it will not serve any purpose.
Let's add some meaningful description to it

2021-02-03 16:29 UTC, EmOlsz commented on code/index.html
> +              href="javascript:void(0);"
You don't need that really - far better approach would be to set `href` value as `#`

2021-02-03 16:29 UTC, EmOlsz commented on code/index.html
> +                ><img
Ups, a bit weird formatting. It should rather be :

```
<a href="./pages/news.html" target="_blank" class="block">
  <img
    src="https://cdn.stocksnap.io/img-thumbs/960w/woman-working_1LXJ2HZ9UY.jpg"
    alt=""
    class="res-img"
  />
</a>
```

2021-02-04 09:01 UTC, takrami commented
Thank you for your helpful review :) Requested changes done.

2021-02-04 11:19 UTC, EmOlsz approved these changes
Thank you for changes, project approved :)

2021-08-10 11:48 UTC, closed without merging