Project 2 News site Caroline Byström
Technigo/project-news-site pull request #162
Opened 2021-01-24 21:07 UTC by Frivridna

Finished the project and hopefully reached somewhere between the blue/red stretch goals. 

I have put things I've struggled with in the README file.

2021-02-03 14:07 UTC, HIPPIEKICK requested changes
Hi Caroline! Good job with this project, I like that you played around with hover effects and the `transition` property 👍 However, I would like to ask you to go through the indentation of  your CSS file as there are many tabs there right now. The idea is that we want VSC to "translate" our tabs to (two) spaces, I made a comment on what your settings should look like. Change this and take a look at the [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) if you're unsure on how the indentation of the CSS file should look.

So to be approved:
- change indentation
- get rid of horizontal scroll caused by too wide content (the buttons in the navbar). Check the inspector if you need.

We’ve also put together some general feedback that applies to many projects this first week. Check it out and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-02-03 14:07 UTC, HIPPIEKICK commented on code/style.css
> +	}
Now I see that they are actually outside the width of the HTML element, meaning your content becomes too wide:

<img width="372" alt="Skärmavbild 2021-02-03 kl  14 58 56" src="https://user-images.githubusercontent.com/51529201/106757179-58403b80-6630-11eb-8ed6-653640d52408.png">

2021-02-03 14:07 UTC, HIPPIEKICK commented on code/style.css
> +		width: 320px;
Just a heads up that this `width` will limit the width of all content:
<img width="659" alt="Skärmavbild 2021-02-03 kl  15 03 22" src="https://user-images.githubusercontent.com/51529201/106757691-f6cc9c80-6630-11eb-9b4f-2ed9deadcb33.png">

2021-04-15 12:32 UTC, Frivridna commented on code/style.css
> +	}
Hello Matilda! Thank you for your comments. I finally got around to make changes in this project :) One question: I set a height to 100vh but in some media views (iPad, iphone x) you can not see the entire length of all content on the page - can I change this somehow?

2021-04-19 09:11 UTC, HIPPIEKICK approved these changes

2021-08-10 11:32 UTC, closed without merging