Technigo Project Week 2 - The News Site
Technigo/project-news-site pull request #166
Opened 2021-01-24 22:48 UTC by idasylven

Project of building a magazine or newspaper site. The site should contain a header with a name of the site, a logo and a navbar. I´m happy with the styling of my project, but my main issue at this point is to tweak the responsive section to that the layout also works for tablet and desktop screens.

2021-02-02 14:14 UTC, HIPPIEKICK commented
Hi Ida! Can you share a link to your deployed project on netlify? :)

2021-02-03 14:57 UTC, idasylven commented
Hi Matilda,

Yes of course! Im sorry you had to reach out and ask for it - my apologies.

Netlify link:
https://pedantic-hugle-09f056.netlify.app/code/

Like I mentioned in the README section my project is not currently
responsive (it is only the mobile view layout that makes sense right now),
which was one of the fundamental requirements. So Im fully aware I wont
pass the assignment for now. I was quite sad and frustrated about when I
submitted, but now Im actually quite happy - because after just one more
week of coding I think I now how to adjust the errors and make it work! And
that feels great!

I have a quick question though: how do you prefer for us to submit the
Netlify link (other than in Canvas)? Because I feel like I have been told
we should edit our README text in the VS code editor, and never in GitHub
because that might cause a conflict. However, you need to push the
completed project into GitHub before publishing on Netlify. So it is a bit
of a catch 22 adding the Netlify link into the project itself in VS-code,
since you wont have it before doing the push. Hope my track of thought
makes sense!

Please let me know and I´ll make sure to follow the procedure you suggest.
Thank you!

Wishing you a lovely day,

Kind regards
Ida Sylvén

On Tue, Feb 2, 2021 at 3:14 PM Matilda Arvidsson <notifications@github.com>
wrote:

> Hi Ida! Can you share a link to your deployed project on netlify? :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-news-site/pull/166#issuecomment-771663288>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ5QZZV3LMXFDQ55RWFSHOLS5ACGFANCNFSM4WQ43MWQ>
> .
>

2021-02-03 16:14 UTC, HIPPIEKICK commented
No worries Ida! That's a good question, it's OK if you just paste it into the pull request free text area (or you could deploy and then push more changes afterwards).

2021-02-03 16:36 UTC, HIPPIEKICK requested changes
Hi again Ida! Since you mentioned that you've realized some things regarding this project, I tried to give you some help along the way with things you can fix in order to make it responsive. In order to be approved:
- fix responsiveness
- correct the indentation of the CSS file

To make it easier for yourself, I would start with revising some of your class names as some classes seem to have the same styling. This will make your CSS less verbose and allow you to make changes to all cards at once (changing the styling in only one place).

We’ve also put together some general feedback that applies to many projects this first week. Focus on the above first but check it out when you find time and take the tips with you to upcoming projects! 👉 [General Feedback - week 2](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/index.html
> +        </div>
Nice and clean cards! Looks like they all have the same styling though 🤔 Just give all cards the same class name in that case and style that one class :)

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/style.css
> +                                                            html {
Oops, some crazy indentation going on in this file 😅 Remove some indentation (should be two spaces). Reach out if you need help with VSC settings, but you should be able to go into Preferences/Settings and then search for indentation, to be able to check the Tab Size (should be 2). Make sure the box is checked that says "Insert spaces when pressing Tab" as well.

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/style.css
> +                                                            html {
A general comment - I guess you've been using the inspector? I use it all the time to check how the content look in all devices. You mentioned that you've only checked how it looks in mobile, but when I check e.g. iPhone X, it looks like the content is too wide (see image).

<img width="440" alt="Skärmavbild 2021-02-03 kl  17 20 09" src="https://user-images.githubusercontent.com/51529201/106776122-14573180-6644-11eb-8e2a-72f4aef81dde.png">

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/style.css
> +                                                                box-shadow: 0px 8px 3px -8px #111, 0px 6px 0px -3px white, 0px 21px 8px -15px #111;
I really like this box-shadow!

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/style.css
> +                                                                    width: 105%;
A width of 105% makes this content too wide - causing a horizontal scroll

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/style.css
> +                                                                    margin-right: -47.5%;
Be careful with negative values as it makes the structure non-logical sometimes. Allocate space in the parent element instead (heading-couture).

2021-02-03 16:36 UTC, HIPPIEKICK commented on code/index.html
> +                <div class="heading-couture">
Hmm, this `div` contains both an `h2` and a `p`. What could be a more descriptive class name for this?

2021-05-08 21:32 UTC, idasylven commented
Thank you very much for all the valuable comments 🙏  I have revised my project, fingers crossed a lot of functionalities and structures are now improved 🤞 💫

2021-05-16 07:10 UTC, KarolCislowski approved these changes
👍🏻

2021-08-10 11:32 UTC, closed without merging