Nazanin's news site
Technigo/project-news-site pull request #175
Opened 2021-03-21 18:32 UTC by nazi-pira

2021-04-20 10:19 UTC, KarolCislowski requested changes
To meet the requirements:
- Publish your site on Netlify and add a link to it to the readme
- Style your page. - You have padding/margin(white frame) around your content 
- Create a responsive design with the following views; Desktop 4 columns, tablet 2 columns, mobile 1 column.
- The site should have a header, the main news article, a grid of news articles.

2021-05-17 13:43 UTC, nazi-pira commented
Fixed

2021-05-17 23:55 UTC, KarolCislowski approved these changes
Nice 😄

2021-05-17 23:55 UTC, KarolCislowski commented on code/style.css
> -html {
You should remember about default margin/padding of your body and HTML. the best way to reset all sneaky box behaviors you can use 
```css
* {
    margin: 0;
    padding: 0;
  }
```

2021-08-10 11:32 UTC, closed without merging