Pull request
Technigo/project-news-site pull request #491
Opened 2024-01-28 21:54 UTC by fridaforser

2024-01-31 13:00 UTC, AntonellaMorittu requested changes
Hi Frida, well done with the pre-course project! Really nice UI, also it fulfills most of the requirements. Make sure you make the app responsibe for all screen sizes from 320px (test with smaller screen sizes and make sure there's no horizontal scrolling). 

As a general improvement, I also recommend using a formatter for css, it will take care of the spacing and indentations. Keep up the good work! 👏

2024-02-02 15:24 UTC, fridaforser commented
Hi @AntonellaMorittu, I have now implemented the changes to make the site more responsive, let me know if it looks good or if I need to change anything else :)

2024-02-07 13:22 UTC, HIPPIEKICK requested changes
Hi! You're already approved, I just need to test something 😇

2024-02-07 13:22 UTC, HIPPIEKICK approved these changes

2024-08-15 12:15 UTC, closed without merging