News-site-libn
Technigo/project-news-site pull request #502
Opened 2024-02-05 07:59 UTC by linaroos

My first project

2024-02-05 08:44 UTC, AntonellaMorittu requested changes
Hi Lina, good job completing your first assignment! Cool choice of concept, I am also watching Love is Blind haha :)
Please make sure that you test your app to be responsive, here from the instructions: 

- Create a responsive design with the following views: Desktop 4 columns, tablet 2 columns, mobile 1 column (it should look good on devices from 320px width up to 1600px).

Update your repository to pass the assignment, thank you 💪

2024-02-05 13:43 UTC, linaroos commented
Hi Antonella, I made the changes, did I get it right?
Many thanks!

2024-02-06 15:59 UTC, AntonellaMorittu requested changes
Hi again 👋 the layout is still not responsive in the correct way. I suggest you check again[ this video](https://www.notion.so/technigo/Pre-Course-Tools-HTML-CSS-Flexbox-Grid-0ed0bd0101db40a2b36e61836a45c5d5?pvs=4#38e91b9aac344138b1b6a278d660fd48) where it's explained how to use grids to achieve the correct layout:

Desktop 4 columns, tablet 2 columns, mobile 1 column (it should look good on devices from 320px width up to 1600px)

Almost there 💪

2024-02-08 12:50 UTC, AntonellaMorittu commented
<img width="1461" alt="Screenshot 2024-02-08 at 13 47 18" src="https://github.com/Technigo/project-news-site/assets/33493978/9fb898c3-40a5-4c76-a284-b46803fe0709">
Hi Lina, you only need to fix the desktop layout now, 4 columns per row! See screenshot :) If you have doubts or questions you can always ask support on the slack channel #code-help or Stack Overflow :)

2024-02-09 11:07 UTC, linaroos commented
Thank you Antonella for all patience, I finally got it 😄

2024-02-14 07:10 UTC, AntonellaMorittu approved these changes
Hi Lina, looks so much better now! yay 🥳

2024-08-15 12:15 UTC, closed without merging